### ISSUE TITLE
standard babel plugin way of use it.

### ISSUE THREAD

**Issue by raulfdm** [TheMagicianDev/babel-plugin-module-resolver-tsconfig#1]
Hey, 👋 

First, thanks for this project, it's really helpful.

I was just wondering if there's any particular reason you'd go with a custom way of setting the plugin up instead the standards of babel?

Current way:
```js
const { setModuleResolverPluginForTsConfig } = require('babel-plugin-module-resolver-tsconfig')

module.export = {
  "presets": [
    "@babel/preset-env",
    "@babel/preset-typescript"
  ],
  "plugins": [
    "@babel/plugin-proposal-class-properties",
    setModuleResolverPluginForTsConfig()
  ]
}
```

Standard babel declaration
```js
module.export = {
  "presets": [
    "@babel/preset-env",
    "@babel/preset-typescript"
  ],
  "plugins": [
    "@babel/plugin-proposal-class-properties",
    [
      'babel-plugin-module-resolver-tsconfig',
      {
        // options
      }  
    ]
  ]
}
```

It's just a genuine curiosity...

Thanks!

**Comment by MohamedLamineAllal** [comment]
@raulfdm It's super late. I didn't get to see this until now. Well, i guess you are bringing up a good point. There was no reason besides i didn't think much when I did it. The way above is just a factory that generates the original plugin config.
I guess it makes sense to follow the Babel plugin format. I just checked. It's simple to wrap up another plugin. I guess I will give it a roll.

**Comment by MohamedLamineAllal** [comment]
@raulfdm, @moddx, @orbiteleven, It's super late. I didn't get to see this until now. Well, I guess you are bringing up a fair point.

I didn't think much when I did it. The way above is just a factory that generates the original plugin config. Simple and Pretty straightforward.

Now after looking. I would say for simplicity reasons. The factory is simpler. We can give a try to implement a plugin that re-uses the original one directly (Only wrapping) if you see it really worth it.

The way I think it can be done. Is to re-use our factory with the exported plugin [L27](https://github.com/tleunen/babel-plugin-module-resolver/blob/ff8a445b3e72358100cf8570c79ecd74265133bd/src/index.js#L27) in the following hacky way.

```js
import moduleResolverPlugin from 'babel-plugin-module-resolver';
// importing the factory

export default (params) => {
      const pluginObj = moduleResolverPlugin(params);
      
      const originalPre = pluginObj.pre.bind(pluginObj);

      pluginObj.name = 'module-resolver-tsconfig';

      pluginObj.pre = function (...args) {
          const [_, options] =  setModuleResolverPluginForTsConfig(this.opts);
          this.opts = options;
          originalPre(...args);
      }.bind(pluginObj);
      
      return pluginObj;
};
```

And you can see it's not straightforward ( check [original plugin L27](https://github.com/tleunen/babel-plugin-module-resolver/blob/ff8a445b3e72358100cf8570c79ecd74265133bd/src/index.js#L27 ) in the following hacky way. ). I wonder if the above would work well.
I may give it a try later.
If you do that before me instead. I would accept the PR. And we can add the plugin option as well.
